import { expect, test } from 'vitest'

import * as index from '../../index.js'

// Pins the runtime surface of the `@openfort/react` entry point. Adding or
// removing an export is a change consumers can see, so it has to be an
// intentional snapshot update rather than a silent side effect.
test('exports', () => {
  expect(Object.keys(index).sort()).toMatchInlineSnapshot(`
    [
      "AccountTypeEnum",
      "ApiRequestError",
      "AuthProvider",
      "AuthenticationError",
      "Avatar",
      "ChainIcon",
      "ChainNotConfiguredError",
      "ChainTypeEnum",
      "ClientNotInitializedError",
      "ConnectorNotFoundError",
      "ConnectorTypeMismatchError",
      "FundingError",
      "FundingMethod",
      "FundingNotConfiguredError",
      "InvalidEmailError",
      "LinkWalletOnSignUpOption",
      "MissingParameterError",
      "NotAuthenticatedError",
      "OAuthProvider",
      "OPENFORT_VERSION",
      "OpenfortButton",
      "OpenfortConfigError",
      "OpenfortError",
      "OpenfortEvents",
      "OpenfortProvider",
      "OtpRequiredError",
      "ProviderNotFoundError",
      "ProviderNotReadyError",
      "RecoveryError",
      "RecoveryMethod",
      "RpcUrlNotConfiguredError",
      "SetActiveWalletError",
      "SiweMessageError",
      "SolanaClusterNotSupportedError",
      "ThirdPartyOAuthProvider",
      "UnsupportedOperationError",
      "ValidationError",
      "WalletConfigNotFoundError",
      "WalletCreationError",
      "WalletError",
      "WalletImportError",
      "WalletNotConnectedError",
      "WalletNotFoundError",
      "createSIWEMessage",
      "cryptoPaymentMethod",
      "embeddedWalletId",
      "formatAddress",
      "getDefaultSolanaRpcUrl",
      "getEmbeddedAccountsQueryOptions",
      "getUserQueryOptions",
      "openfortEvents",
      "openfortKeys",
      "use7702Authorization",
      "useAuthCallback",
      "useEmailAuth",
      "useEmailOtpAuth",
      "useFunding",
      "useFundingMethods",
      "useGrantPermissions",
      "useGuestAuth",
      "useInvalidateBalance",
      "useOAuth",
      "useOnramp",
      "useOpenfort",
      "usePhoneOtpAuth",
      "useRevokePermissions",
      "useSignMessage",
      "useSignOut",
      "useUI",
      "useUser",
    ]
  `)
})
