/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/_showcase'
import { Route as HooksRouteImport } from './routes/_hooks'
import { Route as ShowcaseIndexRouteImport } from './routes/_showcase/index'
import { Route as HooksWagmiRouteImport } from './routes/_hooks/wagmi'
import { Route as HooksSolanaRouteImport } from './routes/_hooks/solana'
import { Route as HooksProviderRouteImport } from './routes/_hooks/provider'
import { Route as ShowcaseShowcaseAuthRouteImport } from './routes/_showcase/showcase/auth'
import { Route as HooksWalletUseSolanaEmbeddedWalletRouteImport } from './routes/_hooks/wallet/useSolanaEmbeddedWallet'
import { Route as HooksWalletUseEthereumWalletAssetsRouteImport } from './routes/_hooks/wallet/useEthereumWalletAssets'
import { Route as HooksWalletUseEthereumEmbeddedWalletRouteImport } from './routes/_hooks/wallet/useEthereumEmbeddedWallet'
import { Route as HooksWagmiUseSwitchChainRouteImport } from './routes/_hooks/wagmi/useSwitchChain'
import { Route as HooksWagmiUseDisconnectRouteImport } from './routes/_hooks/wagmi/useDisconnect'
import { Route as HooksWagmiUseBalanceRouteImport } from './routes/_hooks/wagmi/useBalance'
import { Route as HooksWagmiUseAccountRouteImport } from './routes/_hooks/wagmi/useAccount'
import { Route as HooksUtilsUseUIRouteImport } from './routes/_hooks/utils/useUI'
import { Route as HooksAuthUseWalletAuthRouteImport } from './routes/_hooks/auth/useWalletAuth'
import { Route as HooksAuthUseUserRouteImport } from './routes/_hooks/auth/useUser'
import { Route as HooksAuthUseSignOutRouteImport } from './routes/_hooks/auth/useSignOut'
import { Route as HooksAuthUseOauthRouteImport } from './routes/_hooks/auth/useOauth'
import { Route as HooksAuthUseGuestAuthRouteImport } from './routes/_hooks/auth/useGuestAuth'
import { Route as HooksAuthUseEmailAuthRouteImport } from './routes/_hooks/auth/useEmailAuth'
import { Route as HooksAuthUseConnectWithSiweRouteImport } from './routes/_hooks/auth/useConnectWithSiwe'
import { Route as HooksAuthUseAuthCallbackRouteImport } from './routes/_hooks/auth/useAuthCallback'
import { Route as ShowcaseShowcaseAuthIndexRouteImport } from './routes/_showcase/showcase/auth/index'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/_showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRoute = HooksRouteImport.update({
  id: '/_hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShowcaseRoute,
} as any)
const HooksWagmiRoute = HooksWagmiRouteImport.update({
  id: '/wagmi',
  path: '/wagmi',
  getParentRoute: () => HooksRoute,
} as any)
const HooksSolanaRoute = HooksSolanaRouteImport.update({
  id: '/solana',
  path: '/solana',
  getParentRoute: () => HooksRoute,
} as any)
const HooksProviderRoute = HooksProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => HooksRoute,
} as any)
const ShowcaseShowcaseAuthRoute = ShowcaseShowcaseAuthRouteImport.update({
  id: '/showcase/auth',
  path: '/showcase/auth',
  getParentRoute: () => ShowcaseRoute,
} as any)
const HooksWalletUseSolanaEmbeddedWalletRoute =
  HooksWalletUseSolanaEmbeddedWalletRouteImport.update({
    id: '/wallet/useSolanaEmbeddedWallet',
    path: '/wallet/useSolanaEmbeddedWallet',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksWalletUseEthereumWalletAssetsRoute =
  HooksWalletUseEthereumWalletAssetsRouteImport.update({
    id: '/wallet/useEthereumWalletAssets',
    path: '/wallet/useEthereumWalletAssets',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksWalletUseEthereumEmbeddedWalletRoute =
  HooksWalletUseEthereumEmbeddedWalletRouteImport.update({
    id: '/wallet/useEthereumEmbeddedWallet',
    path: '/wallet/useEthereumEmbeddedWallet',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksWagmiUseSwitchChainRoute =
  HooksWagmiUseSwitchChainRouteImport.update({
    id: '/useSwitchChain',
    path: '/useSwitchChain',
    getParentRoute: () => HooksWagmiRoute,
  } as any)
const HooksWagmiUseDisconnectRoute = HooksWagmiUseDisconnectRouteImport.update({
  id: '/useDisconnect',
  path: '/useDisconnect',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksWagmiUseBalanceRoute = HooksWagmiUseBalanceRouteImport.update({
  id: '/useBalance',
  path: '/useBalance',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksWagmiUseAccountRoute = HooksWagmiUseAccountRouteImport.update({
  id: '/useAccount',
  path: '/useAccount',
  getParentRoute: () => HooksWagmiRoute,
} as any)
const HooksUtilsUseUIRoute = HooksUtilsUseUIRouteImport.update({
  id: '/utils/useUI',
  path: '/utils/useUI',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseWalletAuthRoute = HooksAuthUseWalletAuthRouteImport.update({
  id: '/auth/useWalletAuth',
  path: '/auth/useWalletAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseUserRoute = HooksAuthUseUserRouteImport.update({
  id: '/auth/useUser',
  path: '/auth/useUser',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseSignOutRoute = HooksAuthUseSignOutRouteImport.update({
  id: '/auth/useSignOut',
  path: '/auth/useSignOut',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseOauthRoute = HooksAuthUseOauthRouteImport.update({
  id: '/auth/useOauth',
  path: '/auth/useOauth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseGuestAuthRoute = HooksAuthUseGuestAuthRouteImport.update({
  id: '/auth/useGuestAuth',
  path: '/auth/useGuestAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseEmailAuthRoute = HooksAuthUseEmailAuthRouteImport.update({
  id: '/auth/useEmailAuth',
  path: '/auth/useEmailAuth',
  getParentRoute: () => HooksRoute,
} as any)
const HooksAuthUseConnectWithSiweRoute =
  HooksAuthUseConnectWithSiweRouteImport.update({
    id: '/auth/useConnectWithSiwe',
    path: '/auth/useConnectWithSiwe',
    getParentRoute: () => HooksRoute,
  } as any)
const HooksAuthUseAuthCallbackRoute =
  HooksAuthUseAuthCallbackRouteImport.update({
    id: '/auth/useAuthCallback',
    path: '/auth/useAuthCallback',
    getParentRoute: () => HooksRoute,
  } as any)
const ShowcaseShowcaseAuthIndexRoute =
  ShowcaseShowcaseAuthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShowcaseShowcaseAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShowcaseIndexRoute
  '/provider': typeof HooksProviderRoute
  '/solana': typeof HooksSolanaRoute
  '/wagmi': typeof HooksWagmiRouteWithChildren
  '/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/auth/useConnectWithSiwe': typeof HooksAuthUseConnectWithSiweRoute
  '/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/auth/useUser': typeof HooksAuthUseUserRoute
  '/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/utils/useUI': typeof HooksUtilsUseUIRoute
  '/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/wallet/useEthereumEmbeddedWallet': typeof HooksWalletUseEthereumEmbeddedWalletRoute
  '/wallet/useEthereumWalletAssets': typeof HooksWalletUseEthereumWalletAssetsRoute
  '/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/showcase/auth': typeof ShowcaseShowcaseAuthRouteWithChildren
  '/showcase/auth/': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShowcaseIndexRoute
  '/provider': typeof HooksProviderRoute
  '/solana': typeof HooksSolanaRoute
  '/wagmi': typeof HooksWagmiRouteWithChildren
  '/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/auth/useConnectWithSiwe': typeof HooksAuthUseConnectWithSiweRoute
  '/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/auth/useUser': typeof HooksAuthUseUserRoute
  '/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/utils/useUI': typeof HooksUtilsUseUIRoute
  '/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/wallet/useEthereumEmbeddedWallet': typeof HooksWalletUseEthereumEmbeddedWalletRoute
  '/wallet/useEthereumWalletAssets': typeof HooksWalletUseEthereumWalletAssetsRoute
  '/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/showcase/auth': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hooks': typeof HooksRouteWithChildren
  '/_showcase': typeof ShowcaseRouteWithChildren
  '/_hooks/provider': typeof HooksProviderRoute
  '/_hooks/solana': typeof HooksSolanaRoute
  '/_hooks/wagmi': typeof HooksWagmiRouteWithChildren
  '/_showcase/': typeof ShowcaseIndexRoute
  '/_hooks/auth/useAuthCallback': typeof HooksAuthUseAuthCallbackRoute
  '/_hooks/auth/useConnectWithSiwe': typeof HooksAuthUseConnectWithSiweRoute
  '/_hooks/auth/useEmailAuth': typeof HooksAuthUseEmailAuthRoute
  '/_hooks/auth/useGuestAuth': typeof HooksAuthUseGuestAuthRoute
  '/_hooks/auth/useOauth': typeof HooksAuthUseOauthRoute
  '/_hooks/auth/useSignOut': typeof HooksAuthUseSignOutRoute
  '/_hooks/auth/useUser': typeof HooksAuthUseUserRoute
  '/_hooks/auth/useWalletAuth': typeof HooksAuthUseWalletAuthRoute
  '/_hooks/utils/useUI': typeof HooksUtilsUseUIRoute
  '/_hooks/wagmi/useAccount': typeof HooksWagmiUseAccountRoute
  '/_hooks/wagmi/useBalance': typeof HooksWagmiUseBalanceRoute
  '/_hooks/wagmi/useDisconnect': typeof HooksWagmiUseDisconnectRoute
  '/_hooks/wagmi/useSwitchChain': typeof HooksWagmiUseSwitchChainRoute
  '/_hooks/wallet/useEthereumEmbeddedWallet': typeof HooksWalletUseEthereumEmbeddedWalletRoute
  '/_hooks/wallet/useEthereumWalletAssets': typeof HooksWalletUseEthereumWalletAssetsRoute
  '/_hooks/wallet/useSolanaEmbeddedWallet': typeof HooksWalletUseSolanaEmbeddedWalletRoute
  '/_showcase/showcase/auth': typeof ShowcaseShowcaseAuthRouteWithChildren
  '/_showcase/showcase/auth/': typeof ShowcaseShowcaseAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/provider'
    | '/solana'
    | '/wagmi'
    | '/auth/useAuthCallback'
    | '/auth/useConnectWithSiwe'
    | '/auth/useEmailAuth'
    | '/auth/useGuestAuth'
    | '/auth/useOauth'
    | '/auth/useSignOut'
    | '/auth/useUser'
    | '/auth/useWalletAuth'
    | '/utils/useUI'
    | '/wagmi/useAccount'
    | '/wagmi/useBalance'
    | '/wagmi/useDisconnect'
    | '/wagmi/useSwitchChain'
    | '/wallet/useEthereumEmbeddedWallet'
    | '/wallet/useEthereumWalletAssets'
    | '/wallet/useSolanaEmbeddedWallet'
    | '/showcase/auth'
    | '/showcase/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/provider'
    | '/solana'
    | '/wagmi'
    | '/auth/useAuthCallback'
    | '/auth/useConnectWithSiwe'
    | '/auth/useEmailAuth'
    | '/auth/useGuestAuth'
    | '/auth/useOauth'
    | '/auth/useSignOut'
    | '/auth/useUser'
    | '/auth/useWalletAuth'
    | '/utils/useUI'
    | '/wagmi/useAccount'
    | '/wagmi/useBalance'
    | '/wagmi/useDisconnect'
    | '/wagmi/useSwitchChain'
    | '/wallet/useEthereumEmbeddedWallet'
    | '/wallet/useEthereumWalletAssets'
    | '/wallet/useSolanaEmbeddedWallet'
    | '/showcase/auth'
  id:
    | '__root__'
    | '/_hooks'
    | '/_showcase'
    | '/_hooks/provider'
    | '/_hooks/solana'
    | '/_hooks/wagmi'
    | '/_showcase/'
    | '/_hooks/auth/useAuthCallback'
    | '/_hooks/auth/useConnectWithSiwe'
    | '/_hooks/auth/useEmailAuth'
    | '/_hooks/auth/useGuestAuth'
    | '/_hooks/auth/useOauth'
    | '/_hooks/auth/useSignOut'
    | '/_hooks/auth/useUser'
    | '/_hooks/auth/useWalletAuth'
    | '/_hooks/utils/useUI'
    | '/_hooks/wagmi/useAccount'
    | '/_hooks/wagmi/useBalance'
    | '/_hooks/wagmi/useDisconnect'
    | '/_hooks/wagmi/useSwitchChain'
    | '/_hooks/wallet/useEthereumEmbeddedWallet'
    | '/_hooks/wallet/useEthereumWalletAssets'
    | '/_hooks/wallet/useSolanaEmbeddedWallet'
    | '/_showcase/showcase/auth'
    | '/_showcase/showcase/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HooksRoute: typeof HooksRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_showcase': {
      id: '/_showcase'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hooks': {
      id: '/_hooks'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_showcase/': {
      id: '/_showcase/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/_hooks/wagmi': {
      id: '/_hooks/wagmi'
      path: '/wagmi'
      fullPath: '/wagmi'
      preLoaderRoute: typeof HooksWagmiRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/solana': {
      id: '/_hooks/solana'
      path: '/solana'
      fullPath: '/solana'
      preLoaderRoute: typeof HooksSolanaRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/provider': {
      id: '/_hooks/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof HooksProviderRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_showcase/showcase/auth': {
      id: '/_showcase/showcase/auth'
      path: '/showcase/auth'
      fullPath: '/showcase/auth'
      preLoaderRoute: typeof ShowcaseShowcaseAuthRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/_hooks/wallet/useSolanaEmbeddedWallet': {
      id: '/_hooks/wallet/useSolanaEmbeddedWallet'
      path: '/wallet/useSolanaEmbeddedWallet'
      fullPath: '/wallet/useSolanaEmbeddedWallet'
      preLoaderRoute: typeof HooksWalletUseSolanaEmbeddedWalletRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wallet/useEthereumWalletAssets': {
      id: '/_hooks/wallet/useEthereumWalletAssets'
      path: '/wallet/useEthereumWalletAssets'
      fullPath: '/wallet/useEthereumWalletAssets'
      preLoaderRoute: typeof HooksWalletUseEthereumWalletAssetsRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wallet/useEthereumEmbeddedWallet': {
      id: '/_hooks/wallet/useEthereumEmbeddedWallet'
      path: '/wallet/useEthereumEmbeddedWallet'
      fullPath: '/wallet/useEthereumEmbeddedWallet'
      preLoaderRoute: typeof HooksWalletUseEthereumEmbeddedWalletRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/wagmi/useSwitchChain': {
      id: '/_hooks/wagmi/useSwitchChain'
      path: '/useSwitchChain'
      fullPath: '/wagmi/useSwitchChain'
      preLoaderRoute: typeof HooksWagmiUseSwitchChainRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useDisconnect': {
      id: '/_hooks/wagmi/useDisconnect'
      path: '/useDisconnect'
      fullPath: '/wagmi/useDisconnect'
      preLoaderRoute: typeof HooksWagmiUseDisconnectRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useBalance': {
      id: '/_hooks/wagmi/useBalance'
      path: '/useBalance'
      fullPath: '/wagmi/useBalance'
      preLoaderRoute: typeof HooksWagmiUseBalanceRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/wagmi/useAccount': {
      id: '/_hooks/wagmi/useAccount'
      path: '/useAccount'
      fullPath: '/wagmi/useAccount'
      preLoaderRoute: typeof HooksWagmiUseAccountRouteImport
      parentRoute: typeof HooksWagmiRoute
    }
    '/_hooks/utils/useUI': {
      id: '/_hooks/utils/useUI'
      path: '/utils/useUI'
      fullPath: '/utils/useUI'
      preLoaderRoute: typeof HooksUtilsUseUIRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useWalletAuth': {
      id: '/_hooks/auth/useWalletAuth'
      path: '/auth/useWalletAuth'
      fullPath: '/auth/useWalletAuth'
      preLoaderRoute: typeof HooksAuthUseWalletAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useUser': {
      id: '/_hooks/auth/useUser'
      path: '/auth/useUser'
      fullPath: '/auth/useUser'
      preLoaderRoute: typeof HooksAuthUseUserRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useSignOut': {
      id: '/_hooks/auth/useSignOut'
      path: '/auth/useSignOut'
      fullPath: '/auth/useSignOut'
      preLoaderRoute: typeof HooksAuthUseSignOutRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useOauth': {
      id: '/_hooks/auth/useOauth'
      path: '/auth/useOauth'
      fullPath: '/auth/useOauth'
      preLoaderRoute: typeof HooksAuthUseOauthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useGuestAuth': {
      id: '/_hooks/auth/useGuestAuth'
      path: '/auth/useGuestAuth'
      fullPath: '/auth/useGuestAuth'
      preLoaderRoute: typeof HooksAuthUseGuestAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useEmailAuth': {
      id: '/_hooks/auth/useEmailAuth'
      path: '/auth/useEmailAuth'
      fullPath: '/auth/useEmailAuth'
      preLoaderRoute: typeof HooksAuthUseEmailAuthRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useConnectWithSiwe': {
      id: '/_hooks/auth/useConnectWithSiwe'
      path: '/auth/useConnectWithSiwe'
      fullPath: '/auth/useConnectWithSiwe'
      preLoaderRoute: typeof HooksAuthUseConnectWithSiweRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_hooks/auth/useAuthCallback': {
      id: '/_hooks/auth/useAuthCallback'
      path: '/auth/useAuthCallback'
      fullPath: '/auth/useAuthCallback'
      preLoaderRoute: typeof HooksAuthUseAuthCallbackRouteImport
      parentRoute: typeof HooksRoute
    }
    '/_showcase/showcase/auth/': {
      id: '/_showcase/showcase/auth/'
      path: '/'
      fullPath: '/showcase/auth/'
      preLoaderRoute: typeof ShowcaseShowcaseAuthIndexRouteImport
      parentRoute: typeof ShowcaseShowcaseAuthRoute
    }
  }
}

interface HooksWagmiRouteChildren {
  HooksWagmiUseAccountRoute: typeof HooksWagmiUseAccountRoute
  HooksWagmiUseBalanceRoute: typeof HooksWagmiUseBalanceRoute
  HooksWagmiUseDisconnectRoute: typeof HooksWagmiUseDisconnectRoute
  HooksWagmiUseSwitchChainRoute: typeof HooksWagmiUseSwitchChainRoute
}

const HooksWagmiRouteChildren: HooksWagmiRouteChildren = {
  HooksWagmiUseAccountRoute: HooksWagmiUseAccountRoute,
  HooksWagmiUseBalanceRoute: HooksWagmiUseBalanceRoute,
  HooksWagmiUseDisconnectRoute: HooksWagmiUseDisconnectRoute,
  HooksWagmiUseSwitchChainRoute: HooksWagmiUseSwitchChainRoute,
}

const HooksWagmiRouteWithChildren = HooksWagmiRoute._addFileChildren(
  HooksWagmiRouteChildren,
)

interface HooksRouteChildren {
  HooksProviderRoute: typeof HooksProviderRoute
  HooksSolanaRoute: typeof HooksSolanaRoute
  HooksWagmiRoute: typeof HooksWagmiRouteWithChildren
  HooksAuthUseAuthCallbackRoute: typeof HooksAuthUseAuthCallbackRoute
  HooksAuthUseConnectWithSiweRoute: typeof HooksAuthUseConnectWithSiweRoute
  HooksAuthUseEmailAuthRoute: typeof HooksAuthUseEmailAuthRoute
  HooksAuthUseGuestAuthRoute: typeof HooksAuthUseGuestAuthRoute
  HooksAuthUseOauthRoute: typeof HooksAuthUseOauthRoute
  HooksAuthUseSignOutRoute: typeof HooksAuthUseSignOutRoute
  HooksAuthUseUserRoute: typeof HooksAuthUseUserRoute
  HooksAuthUseWalletAuthRoute: typeof HooksAuthUseWalletAuthRoute
  HooksUtilsUseUIRoute: typeof HooksUtilsUseUIRoute
  HooksWalletUseEthereumEmbeddedWalletRoute: typeof HooksWalletUseEthereumEmbeddedWalletRoute
  HooksWalletUseEthereumWalletAssetsRoute: typeof HooksWalletUseEthereumWalletAssetsRoute
  HooksWalletUseSolanaEmbeddedWalletRoute: typeof HooksWalletUseSolanaEmbeddedWalletRoute
}

const HooksRouteChildren: HooksRouteChildren = {
  HooksProviderRoute: HooksProviderRoute,
  HooksSolanaRoute: HooksSolanaRoute,
  HooksWagmiRoute: HooksWagmiRouteWithChildren,
  HooksAuthUseAuthCallbackRoute: HooksAuthUseAuthCallbackRoute,
  HooksAuthUseConnectWithSiweRoute: HooksAuthUseConnectWithSiweRoute,
  HooksAuthUseEmailAuthRoute: HooksAuthUseEmailAuthRoute,
  HooksAuthUseGuestAuthRoute: HooksAuthUseGuestAuthRoute,
  HooksAuthUseOauthRoute: HooksAuthUseOauthRoute,
  HooksAuthUseSignOutRoute: HooksAuthUseSignOutRoute,
  HooksAuthUseUserRoute: HooksAuthUseUserRoute,
  HooksAuthUseWalletAuthRoute: HooksAuthUseWalletAuthRoute,
  HooksUtilsUseUIRoute: HooksUtilsUseUIRoute,
  HooksWalletUseEthereumEmbeddedWalletRoute:
    HooksWalletUseEthereumEmbeddedWalletRoute,
  HooksWalletUseEthereumWalletAssetsRoute:
    HooksWalletUseEthereumWalletAssetsRoute,
  HooksWalletUseSolanaEmbeddedWalletRoute:
    HooksWalletUseSolanaEmbeddedWalletRoute,
}

const HooksRouteWithChildren = HooksRoute._addFileChildren(HooksRouteChildren)

interface ShowcaseShowcaseAuthRouteChildren {
  ShowcaseShowcaseAuthIndexRoute: typeof ShowcaseShowcaseAuthIndexRoute
}

const ShowcaseShowcaseAuthRouteChildren: ShowcaseShowcaseAuthRouteChildren = {
  ShowcaseShowcaseAuthIndexRoute: ShowcaseShowcaseAuthIndexRoute,
}

const ShowcaseShowcaseAuthRouteWithChildren =
  ShowcaseShowcaseAuthRoute._addFileChildren(ShowcaseShowcaseAuthRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  ShowcaseShowcaseAuthRoute: typeof ShowcaseShowcaseAuthRouteWithChildren
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  ShowcaseShowcaseAuthRoute: ShowcaseShowcaseAuthRouteWithChildren,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HooksRoute: HooksRouteWithChildren,
  ShowcaseRoute: ShowcaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
