export { default as getDefaultConfig } from './defaultConfig.js'
export { default as getDefaultConnectors } from './defaultConnectors.js'
export { embeddedWalletConnector, setEmbeddedWalletProvider } from './embeddedConnector.js'
export { OpenfortWagmiBridge } from './OpenfortWagmiBridge.js'
export { useChainIsSupported } from './useChainIsSupported.js'
export { useChains } from './useChains.js'
export { useConnectWithSiwe } from './useConnectWithSiwe.js'
export { EmbeddedWalletWagmiSync } from './useEmbeddedWalletWagmiSync.js'
export type { AvailableWallet } from './useWalletAuth.js'
export { useWalletAuth } from './useWalletAuth.js'
